### ISSUE TITLE
Quality of produced HTML

### ISSUE THREAD

**Issue by Sidoine** [skclusive/Skclusive.Material.Component#10]
The produced HTML has a number of issues :
* A lot of empty comments
* A lot of <style/> tags at the start of the document that should be in head.

**Comment by skclusive** [comment]
yes. they styles are componentized not produced as css file. and also styles are rendered along with the app. we could do Portal behaviour after rendering move the style elements to head. but i do not see why it is really needed.

could you please explain if possible, what is the potential issue?

**Comment by Sidoine** [comment]
I try to use both BlazorStyled and this package, but the package styles takes precedence over those defined by BlazorStyled because they are declared later.

**Comment by viniwrubleski** [comment]
I had a similar issue in my application, and ended up writing a script to concat all the styles in a css: https://gist.github.com/viniwrubleski/6067cac2b730bda75ddfc6cc8cc841b6#file-materialstyles-ps1

It works without problems.
Maybe this can be put in the release?

**Comment by skclusive** [comment]
@viniwrubleski this looks nice. CSS Isolation will be part of next blazor preview release (i guess in a week). so planning to migrate the style components. hope that will solve the issue.
