### ISSUE TITLE
Other controls

### ISSUE THREAD

**Issue by Mhirji** [skclusive/Skclusive.Material.Component#11]
Do you have any plans to do the following components?

https://material-ui.com/components/selects/
https://material-ui.com/components/pagination/

Thanks!!

**Comment by skclusive** [comment]
yes. adding more components from material-ui is next major work. would you like to contribute any of the components? feel free to do so.

**Comment by skclusive** [comment]
I guess the `<Backdrop />` component already available under `Modal` project. could you please try if you could achieve the demo https://material-ui.com/components/backdrop/?

**Comment by Mhirji** [comment]
Backdrop works! I had tried it on a  different project, not sure why it did not then.  Anyways, I need to get somewhere with a project and after that I can look at contributing in for sure.  Thanks!!

**Comment by skclusive** [comment]
Sure. No issues. Welcome anytime.

**Comment by skclusive** [comment]
closing it now. will be tracked along with #19 when we start developing Pagination and Select.
