### ISSUE TITLE
Styled - ambiguous reference

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#13]
I'm getting a spam of following errors after including the projects and compiling.
> CS0104	'Styled' is an ambiguous reference between 'BlazorStyled.Styled' and 'Skclusive.Core.Component.Styled'	Paragon.Tedis.Mobile	D:\...\Shared\MainLayout.razor

Am I doing something wrong? If not, it would be nice if Skclusive.Core.Component.Styled could be renamed, since writing <BlazorStyled.Styled></BlazorStyled.Styled> everywhere is quite annoying and both are included globally so it's not easy to manage. Or is there some good solution to this?

Edit:
I'm also getting this:

> Multiple components use the tag 'Styled'. Components: BlazorStyled.Styled, BlazorStyled.Styled, Skclusive.Core.Component.Styled, Microsoft.AspNetCore.Components.Bind

There are hundreds of those...

**Comment by skclusive** [comment]
oh. ok. i am open for name change. as of now does not have real functionality underneath with `Styled`.
so for now you can write it as regular `<style>` element.

**Comment by skclusive** [comment]
CSS Isolation is coming in next blazor preview. so styling would be updated based on the feature.

**Comment by skclusive** [comment]
CSS Isolation seems not usable as we compose components instead of html only components. neverthless styling is updated and powered by DI now. 

Styled class has been removed from Skclusive.Core.Component. breaking change it 3.0.0.

closing the issue.
