### ISSUE TITLE
Script.csproj fails build when packages are not installed

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#16]
Pretty much what's in the title. There's `npm run build` command but no installation command.

**Comment by skclusive** [comment]
do we add npm install followed by npm run build?

**Comment by esso23** [comment]
Yeah, when I added
`<Exec Command="npm i" />`
it works just fine.

**Comment by skclusive** [comment]
great. can you raise pull request?

**Comment by esso23** [comment]
Sure.

**Comment by skclusive** [comment]
could you please make is "npm install". "npm i" might be less readable

**Comment by skclusive** [comment]
great. thanks for the contribution. welcome on board :-)
