### ISSUE TITLE
There is no registered service of type 'Skclusive.Script.DomHelpers.DomHelpers'

### ISSUE THREAD

**Issue by ahmetsekmen** [skclusive/Skclusive.Material.Component#18]
I am getting this error.

Unhandled exception rendering component: Cannot provide a value for property 'DomHelpers' on type 'Skclusive.Material.Button.ButtonBase'. There is no registered service of type 'Skclusive.Script.DomHelpers.DomHelpers'.

I have registered 
@using Skclusive.Material.Button
@using Skclusive.Script.DomHelpers

It may can be a bug. Some other components are working

**Comment by skclusive** [comment]
are you doing the server side or client side blazor?

you may need to add this in Startup.ConfigureServices for Service Side.

```csharp
using Skclusive.Material.Component;

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddRazorPages();
        services.AddServerSideBlazor();
        // ...
        services.TryAddMaterialServices(new MaterialConfigBuilder().Build());
    }
}
```

**Comment by skclusive** [comment]
and for client side blazor,

```csharp
using Skclusive.Material.Component;

public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);

        builder.RootComponents.Add<App>("app");

        builder.Services.TryAddMaterialServices(new MaterialConfigBuilder().Build());

        await builder.Build().RunAsync();
    }
}
```

**Comment by ahmetsekmen** [comment]
It worked thanks!

**Comment by skclusive** [comment]
great. closing this.
