### ISSUE TITLE
New Components

### ISSUE THREAD

**Issue by skclusive** [skclusive/Skclusive.Material.Component#19]
Next set of components to be implemented. just a holder issue to track. 

Not in any order. People who are interested in contributing can create separate issue for respective components and work on it.

1. Select
2. Pagination
3. Tooltip #12 
4. GridList
5. ButtonGroup
6. Slider
7. Bottom Navigation
8. Breadcrumbs
9. Snackbar
10. Alert
11. Autocomplete
12. Rating
13. TreeView
14. Stepper #32

**Comment by srxqds** [comment]
when will those compopent release in schedule?

**Comment by skclusive** [comment]
@srxqds targeting for .NET 5 timeline. if not all, as much as possible. looking for contributions.

**Comment by skclusive** [comment]
closing this issue in favour of https://github.com/skclusive/Skclusive.Material.Component/issues/41
