### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ofrades** [skclusive/Skclusive.Material.Component#2]
Can you point me to documentation on how to use the Material.Component?

**Comment by Mhirji** [comment]
I just came across this library and it seems really promising.  However I do agree with @ofrades that it would be really helpful if there is a documentation site like material-ui.  I started to figure it out based on the sample projects, but following the dependency structure based on what is there can be a little confusing.  For example, I see that there is a theme object, but not sure if the theme can be customized except by overriding the css with !important everywhere.

**Comment by skclusive** [comment]
@ofrades sorry for the late reply. i didn't notice issue. :(

thanks for interest using the project. yes i have already started working on documentation site similar to Material-UI (almost same as possible).

https://github.com/skclusive/Skclusive.Material.Docs i am actively committing code in develop branch. 

 you can check out these video about what is coming.

[Documentation App](https://www.youtube.com/watch?v=p2iVsZvLPy4&t=1s)

[Documentation source view](https://www.youtube.com/watch?v=YQ3HcyBejs8)

[Theming](https://www.youtube.com/watch?v=qj3h2wklN70)

**Comment by skclusive** [comment]
@Mhirji thanks for interest using the project. the components support Class and Style parameters and Nested Class and Style parameters. so without !important custom styles can be applied. In documentation there will be iOS style switch just using css.

And unlike CSS in JS in react Material-UI, i have used standard CSS and CSS Variables for styling and theming which performs better (theme change doest re-render all the components)

**Comment by skclusive** [comment]
documentation preview is hosted in github pages https://skclusive.github.io/Skclusive.Material.Docs/  (home page needs update)

do let me know your comments.

**Comment by HeroSpha** [comment]
Im enjoying this, i have an issue with text inputs when deployed to Azure Web App. There is too much delay when im typing and some character get deleted. i will make a video and show you what im talking about. When im running local everything works perfect.

**Comment by skclusive** [comment]
@HeroSpha hi. thanks for trying this out. the textfield being slow would be due to the oninput (on each key) event used to update the field and call OnChange callback to match the API of react based text field. Hence over network it would be slow. I guess better to provide way to control which event is considered for field change.

**Comment by skclusive** [comment]
documentation app is implemented and hosted. available at https://skclusive.github.io/Skclusive.Material.Docs/
