### ISSUE TITLE
Hidden component does not work

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#21]
How to reproduce:
Create an empty Blazor server-side project, install Hidden component, include in Imports and paste this to MainLayout:
```html
    <Hidden SmallDown>
        <p>SMALL DOWN</p>
    </Hidden>
    
    <Hidden MediumUp>
        <p>MEDIUM UP</p>
    </Hidden>
```

Both texts will be displayed at all times.

**Comment by skclusive** [comment]
Hidden component generate context class which needs to be passed to the child content. (in blazor we can not modify child content as of now). so could you please try the following.

```html
    <Hidden SmallDown>
        <p class="@context.Class">SMALL DOWN</p>
    </Hidden>
    
    <Hidden MediumUp>
        <p class="@context.Class">MEDIUM UP</p>
    </Hidden>

```
the documentation demo's have these code snippets. may be need to update the Hidden documentation content though.

**Comment by esso23** [comment]
Ah ok. This whole context "thing" makes me a little confused.
Anyway, wouldn't it be simpler to just change the implementation to use <div> and style the div? It would be possible to get rid of Component.Core dependency and the entire inheritance. Material-UI has it implemented that way.

**Comment by skclusive** [comment]
yes. initially i implemented with a wrapper `<div />` only. but i was affecting the layout composition when used. what i mean is when you are designing page layouts and adding `<Hidden/>` introduced additional `<div />`. and `context` in blazor is much more intuitive (in component composition) than render props in `react`.  hence choose to avoid additional div.

may be we could provide either option which parameters to classify.

could you explain about getting rid of Component.Core dependency and inheritance stuff. do you see any issues in general?

**Comment by esso23** [comment]
Yeah, adding a Wrap bool property would be nice, if true it would just wrap it in a div without the need to set context. I've seen this approach in other libraries (MatBlazor - tooltip component i think).

Minimizing dependencies in a library is always a good thing. Anyway, I guess it's needed because of the class/style properties.

**Comment by skclusive** [comment]
sure. will can add Wrap bool property. and conditionally implement. yes. the core component provides the consistent Class/Style properties for all components and the dynamic `<Component />` component. let me close this issue and open new issue for implementing Wrap for Hidden.
