### ISSUE TITLE
TabPanel component not available

### ISSUE THREAD

**Issue by rosspetev** [skclusive/Skclusive.Material.Component#26]
I'd like to make use of the Tabbing components as seen here: https://skclusive.github.io/Skclusive.Material.Docs/tabs

Sample usage from docs:
```
<TabPanel
        Id="vertical-tabpanel"
        Label="vertical-tab"
        Value="@Value"
        Index="1">
        Item One
    </TabPanel>
```

The TabPanel component is not recognised however and I'm not able to find it as part of the source on here. Am I missing something or this has been removed?

**Comment by skclusive** [comment]
`<TabPanel />` is user defined component. it could be anything similar to that used in Skclusive-UI Tabs.

you can find the `<TabPanel />` source here. https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Tabs/Segments/TabPanel/TabPanel.razor

thanks for trying out skclusive-ui. let me know if you need more details.

**Comment by rosspetev** [comment]
Awesome! Some useful stuff in the docs project too. Thanks for your efforts, great work.

**Comment by skclusive** [comment]
thanks for closing it. the Docs project could be considered one of the biggest Blazor project live as of now. there are lots of pages and demo components there.
