### ISSUE TITLE
ListItem link with Button

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#27]
How to forward Href parameter when using `<ListItem Button>`?
Using Compoent="a" is not a good solution since the styling is not alright.

**Comment by skclusive** [comment]
i guess the attribute href will behave as link in `<a />` only. hence whether it is `<ListItem />` or `<Button />` the rendered component need to be `<a />` to have `href`. i guess this is same behaviour in material-ui. 

could you please explain the stying issue?

**Comment by esso23** [comment]
When you hover over it, it looks different. The text turns red. The button has a Href parameter so it would be nice to to be able to forward the Href somehow to the Button component, like this:
`<ListItem Href="something">` - although I'm not sure if this is the best approach. In Material-UI you can do this:
`<ListItem component={Link} to="/home">`

**Comment by skclusive** [comment]
i guess there are other global css affecting the behaviour of `<a />` on hover. could you inspect the element in chrome dev tool (choose the :hover) checkbox and inspect the styles applied?

yea. need to try it out accepting `Type` and 'string' for component.

**Comment by esso23** [comment]
OK, it was just a stupid mistake on my side. I automatically removed the Button parameter as I added Component="a" for some reason (I think I just misunderstood the concept). Understood it when I inspected the HTML.
