### ISSUE TITLE
TextField MaxLength

### ISSUE THREAD

**Issue by mariohik** [skclusive/Skclusive.Material.Component#29]
How can I set the maxlength of a input? (TextField)

**Comment by skclusive** [comment]
noticed that it is not possible to pass as of now from TextField. it is a bug. will be fixed. thanks for reporting

**Comment by skclusive** [comment]
issue fixed in develop branch. would be included in next patch release.

**Comment by skclusive** [comment]
fixed in 5.1.0 release.

**Comment by skclusive** [comment]
closing the issue now. feel free to re-open if required.
