### ISSUE TITLE
Does OnClick for TableRow work?

### ISSUE THREAD

**Issue by win32nipuh** [skclusive/Skclusive.Material.Component#3]
How to catch row selection on click and call my own function?
For example,

user clicks on row, the row is selected and the row details displayed in other component.
user selects row and wants to download the object or print it etc.
Something like this is partially implemented in
https://github.com/gustavnavar/Grid.Blazor

It is
I.e. on row click OrderDetail component called.

**Comment by skclusive** [comment]
<TableRow> component supports "OnClick" handler which can be used to enable the Other Components (OrderDetails) when selected. about to complete the ongoing documentation work. you can check what is coming in this video. https://www.youtube.com/watch?v=p2iVsZvLPy4&t=90s it will have samples for all components and API info.

**Comment by skclusive** [comment]
documentation app is implemented and hosted. available at https://skclusive.github.io/Skclusive.Material.Docs/

you can check the Table section for usage
