### ISSUE TITLE
Add theme

### ISSUE THREAD

**Issue by cpfk** [skclusive/Skclusive.Material.Component#31]
How can I add a modern-ui theme? Do I have to change the source code?

Thank you for your work on this library.

**Comment by Mhirji** [comment]
I had asked this question here: https://github.com/skclusive/Skclusive.Material.Docs/issues/4

**Comment by cpfk** [comment]
Thank you

On May 20, 2020, at 6:51 PM, Mhirji <notifications@github.com> wrote:

﻿

I had asked this question here: skclusive/Skclusive.Material.Docs#4<https://github.com/skclusive/Skclusive.Material.Docs/issues/4>

**Comment by skclusive** [comment]
ThemeProvider updated to received theme configuration equivalent to material-ui configuration. we could serialize the material-ui json to ThemeConfig.

```cs
public static ThemeConfig Light = new ThemeConfig
    {
        Palette = new PaletteConfig
        {
            Type = PaletteType.Light,

            Primary = new PaletteColorConfig
            {
                Main = PaletteColors.Blue.X700
            },

            Secondary = new PaletteColorConfig
            {
                Main = PaletteColors.Pink.A400.Darken(0.1m)
            }
        }
    };

```

**Comment by skclusive** [comment]
closing this as implemented. need to update docs.
