### ISSUE TITLE
TextField two-way binding

### ISSUE THREAD

**Issue by CsabaStupak** [skclusive/Skclusive.Material.Component#33]
I'm trying to two-way bind the `TextField.Value` but for some reason it does not work. Here is my code:

```
        <TextField Label="Anything" Type="text" Variant="@TextFieldVariant.Filled"
                                   @bind-Value="@Name" OnChange="OnNameChanged"/>

        private string m_str = "Hello";
        private string Name
        {
            get { return m_str; }
            set
            {
                m_str = value;
            }
        }

        private void OnNameChanged(ChangeEventArgs args)
        {
            string temp = Name;
            temp = args.Value?.ToString();
            temp = null;
        }
```

This is a server-side application. The Name.get method is called and used by the `TextField`, however the set method is never called. Interesting that the `OnNameChanged` is called but the Name is always the original "Hello".

The same code with `InputText` works however.

Can you help me what am I doing wrong?
Thanks! :-)

PS: Great job with this library :-)

**Comment by skclusive** [comment]
hi. thanks.

currently the components are not @bind friendly. when you are using bind you might not need the change handler. 

can you try the below code?

```html
        <TextField
               Label="Anything"
              Type="text"
              Variant="@TextFieldVariant.Filled"
              Value="@Name"
             OnChange="OnNameChanged" />

        private string m_str = "Hello";
        private string Name
        {
            get { return m_str; }
            set
            {
                m_str = value;
            }
        }

        private void OnNameChanged(ChangeEventArgs args)
        {
            Name = args.Value?.ToString();
        }

```

**Comment by CsabaStupak** [comment]
I'm coming to Blazor from WPF where two-way binding is heavily used and IMHO makes the code simpler - at least for me :-)
I understand - today this is a limitation.

**Comment by skclusive** [comment]
sure. i understand that. as this library relied on react way of data flow and when i started that time blazor bind was not there. hence not tested bind feature. should be easy to identify and fix that. will do in next release

**Comment by 4nTrax** [comment]
Next release you mean version 3.0 of your components? Would be great!

**Comment by skclusive** [comment]
Binding is added in 5.1.0 release.

```html
<TextField 
          Label="Anything"
          Type="text"
          Variant="@TextFieldVariant.Filled"
          @bind-Value="@Name" />

@code 
{
     private string Name { set; get; }
}
```

**Comment by skclusive** [comment]
closing the issue now. feel free to re-open if required.
