### ISSUE TITLE
[Global] CultureInfo issue when converting double to string

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#34]
I had a problem with Menu sometimes displaying in the corner even with AnchorRef correctly set.
Found the problem in Popover.cs in `GetPositioningStylesAsync`. There's this line:
```cs
styles.Add("left", $"{left}px");
```
In my CultureInfo, which is Slovak, or sk-SK, it is translated to "1296,5px" (comma instead of dot) which is not valid CSS. I fixed it in my code like this:
```cs
styles.Add("left", $"{left.ToString(CultureInfo.InvariantCulture)}px");
```
which is a thing I have to always use with floating point numbers. I guess this is going to be a global issue, so I'm not gonna create a PR for this small fix which fixes it in only one place.

**Comment by skclusive** [comment]
oh. not aware of this. this need to be fixed through out the code base where ever used. thanks for reporting.

**Comment by skclusive** [comment]
patch version released with fix https://www.nuget.org/packages/Skclusive.Material.Component/2.0.1. closing the issue.
