### ISSUE TITLE
Card @onclick not working

### ISSUE THREAD

**Issue by Natromitus** [skclusive/Skclusive.Material.Component#35]
Hello,
I tried using `OnClick` on Card component, but that just doesn't work.
By what I understand `OnClick` isn't implemented on Card Component
so I tried to use `@onclick`.

Razor:
```
<Card Class="game-card-root"
      @onclick="@(e => HandleClickAsync(e))">
      ...
</Card>
```
Code:
```
[Parameter] public EventCallback Clicked { get; set; }
private async Task HandleClickAsync(MouseEventArgs args)
{
    await Clicked.InvokeAsync(args);
}
```
Error I get:
 _InvalidOperationException: Unable to set property 'onclick' on object of type 'Skclusive.Material.Card.Card'. The error was: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback\`1[Microsoft.AspNetCore.Components.Web.MouseEventArgs]' to type 'Microsoft.AspNetCore.Components.EventCallback\`1[System.EventArgs]'._

**Comment by skclusive** [comment]
yes. Card component https://github.com/skclusive/Skclusive.Material.Component/blob/master/Card/src/Card/Card.razor does not pass the OnClick handler to the Paper component.

it is kind of tricky in blazor that what all event handlers should be made available. if we try to support all the DOM handlers and if we pass event handlers from one component to another component, i guess lots of event handlers (wrappers from parent component) created.

need to find balanced approach and at least enable basic event handlers.

for now you can workaround with a wrapper div.

```html
<div @onclick="@(e => HandleClickAsync(e))">
     <Card Class="game-card-root">
      ...
      </Card>
</div>

```

**Comment by skclusive** [comment]
fixed in develop branch. closing the issue
