### ISSUE TITLE
SideBar does not open on page load for browser host

### ISSUE THREAD

**Issue by ngreneaux** [skclusive/Skclusive.Material.Component#37]
Love the components!

One thing i am running into is that when using blazor webassembly i cannot get the dashboard to work correctly when CascadingAuthenticationState is added to the DashboardView.razor.

The dashboard loads but the sidebar does not pop out unless i adjust the size of the browser window.

This is ONLY a problem for Browser Hosted AND ONLY when i am using CascadingAuthenticationState.

**Comment by ngreneaux** [comment]
Sorry I think i posed this under the wrong project.. I believe this belong in the Layout project.

**Comment by skclusive** [comment]
@ngreneaux no issues. you can raise here as well. sorry for reaching late. could you share a minimal reproducible repo in git?

**Comment by skclusive** [comment]
do you still have the issue? i had used ```<CascadingAuthenticationState />``` with Skclusive-UI. 

closing the issue now. please reopen in case reproduced. thanks.
