### ISSUE TITLE
How to replace icon in the toolbar?

### ISSUE THREAD

**Issue by win32nipuh** [skclusive/Skclusive.Material.Component#4]
I have created a test app using Skclusive Io framework. 
Is it possible to replace svg icon in the left corner of the toolbar with my own? How to do it?
Thnx

**Comment by skclusive** [comment]
hi. as of now not possible. I am going to make it configurable. the app icon is coming from Skclusive.Material.Layout used in samples. will fix this and update the issue.

**Comment by win32nipuh** [comment]
yes,  it will be great. Developer can add his buttons to the toolbar etc

**Comment by skclusive** [comment]
yes. toolbar items will be configurable.

**Comment by win32nipuh** [comment]
When you plan to release the version with these changes? Approximately

**Comment by skclusive** [comment]
By next weekend. Due to ongoing documentation effort.

**Comment by skclusive** [comment]
documentation app is implemented and hosted. available at https://skclusive.github.io/Skclusive.Material.Docs/

This issue is specific to Skclusive.Material.Layout project. which has been updated to include custom Toolbar items.

you can check the usage with custom logo, title and action items here

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Layout/AppLayout.razor

**Comment by win32nipuh** [comment]
Thank you, it looks great. 
One question: 
you wrote "Sample projects using Skclusive.Material.Component are availabe in Skclusive.Blazor.Samples repository."

But each sample used Logo and title "Devias Kit" etc.
I have downloaded the Dashboard Sample to check how i can customize the App Bar but it is still the old version. Do you plan to modify samples to show how to work with App Bar etc?

**Comment by skclusive** [comment]
could you please clone/download the latest samples. currently i have made a 2.0.0-rc release.

after downloading, you can replace the AppLogo.razor (https://github.com/skclusive/Skclusive.Blazor.Samples/blob/master/Skclusive.Blazor.Dashboard/Dashboard.App.View/Logo/AppLogo.razor) file content with <img with src.


https://github.com/skclusive/Skclusive.Blazor.Samples/blob/master/Skclusive.Blazor.Dashboard/Dashboard.App.View/Layout/FullLayout.razor

```html
<MainLayout>
    <LogoContent>
       <AnyCustomLogoOrImageTagHere>
    </LogoContent>
    <TitleContent>
        <Typography
            Style="flex-grow: 1; margin-left: 20px;"
            Variant="@TypographyVariant.H6"
            NoWrap>
            Your Title Here
        </Typography>
    </TitleContent>
  <SidebarContent>
  ....
 </SidebarContent>
<BodyContent>
   @Body
</BodyContent>
</MainLayout>
```

let me know if you have any more doubt.

**Comment by win32nipuh** [comment]
Sorry, sometimes I do not know where to create issues :-)
Please take a look at
https://github.com/skclusive/Skclusive.Material.Docs/issues/3

**Comment by skclusive** [comment]
no issues. yea. me too bit confused at the moment. :-)

anything related to the Skclusive-UI components is here https://github.com/skclusive/Skclusive.Material.Component/

anything related to documentation of the Skclusive-UI components to go in https://github.com/skclusive/Skclusive.Material.Docs/

anything related to Layout used in samples either in https://github.com/skclusive/Skclusive.Material.Layout or https://github.com/skclusive/Skclusive.Material.Samples. 

Not a big deal for now though.

**Comment by win32nipuh** [comment]
I have tried to replace icon with my own png  in the 
https://github.com/skclusive/Skclusive.Material.Docs/
to test how it works.
I have replaced the SkclusiveLogo.razor content:

```
@namespace Skclusive.Material.Docs.App.View
<img src="./_content/Skclusive.Material.Docs.App.View/images/pm2.png" width="136" />

```
But it does not work.
Is there another way?

**Comment by skclusive** [comment]
That seems correct. Could you explain what is the error? Image not found? Or image element not rendered?

**Comment by win32nipuh** [comment]
> Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Components.dll
> 'Skclusive.Material.Docs.Server.Host.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Diagnostics.StackTrace.dll'. 
> 'Skclusive.Material.Docs.Server.Host.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Reflection.Metadata.dll'. 
> 'Skclusive.Material.Docs.Server.Host.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Collections.Immutable.dll'. 
> Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Object of type 'Skclusive.Material.Docs.App.View.SkclusiveLogo' does not have a property matching the name 'Title'.

**Comment by skclusive** [comment]
are you passing "Title" property from AppLayout.razor?


```html
'Skclusive.Material.Docs.App.View.SkclusiveLogo' does not have a property matching the name 'Title'.
```

following approachs can be taken:

either:

```html

SkclusiveLogo.razor

@namespace Skclusive.Material.Docs.App.View

<img title="@Title" src="./_content/Skclusive.Material.Docs.App.View/images/pm2.png" width="136" />

@code {
  [Parameter]
  public string Title { set; get; }
}

```

or:

```html
SkclusiveLogo.razor

@namespace Skclusive.Material.Docs.App.View
@inherits MaterialComponentBase

<img src="./_content/Skclusive.Material.Docs.App.View/images/pm2.png" width="136" @attributes="Attributes" />

```

**Comment by win32nipuh** [comment]
ok, thnx. I have tried: 

System.InvalidOperationException: Object of type 'Skclusive.Material.Docs.App.View.SkclusiveLogo' does not have a property matching the name 'Class'.

**Comment by skclusive** [comment]
then you have to extend from 
```html
@inherits MaterialComponentBase

<img class="@_Class" style="@_Style" src="./_content/Skclusive.Material.Docs.App.View/images/pm2.png" width="136" @attributes="Attributes" />


```

so in from other components, you can do.

```html
<SkclusiveLogo Class="some-class" Style="custom-style" />
```

**Comment by win32nipuh** [comment]
Thnx, finally it works, the logo image appears, another question about scaling.
