### ISSUE TITLE
Chip and ChipSet

### ISSUE THREAD

**Issue by henon** [skclusive/Skclusive.Material.Component#42]
I started working on a Chip implementation because it is a fairly simple component and thus ideal for me to learn what it takes to add components to this library. 

![image](https://user-images.githubusercontent.com/44090/84682757-683acc00-af36-11ea-975f-e9d21ee65310.png)

The code is still incomplete but already PRed as #44

**Comment by henon** [comment]
@skclusive I have this problem that the ripple doesn't show. Instead I see a thick black border on click
![image](https://user-images.githubusercontent.com/44090/84818928-8cbaa500-b017-11ea-8484-32af3b341955.png)

Since it happens with `<Button>` too (which I haven't changed) I guess it means I didn't import something, but I can't figure out what I'm missing. 

I can not import all styles at once because that won't compile for some reason. Instead I try to selectively import the right selection of styles, like a-la-carte:
 
```razor
<MaterialScripts />
@*<MaterialStyles />*@

@*<ThemeProvider Theme="@Theme.Dark" />*@

<ChipStyle />
<IconStyles />
<ButtonStyles />
<TouchRippleStyle/>
<RippleStyle/>
```

Maybe you have had this problem and instantly know what I missed?

**Comment by henon** [comment]
OK, The black border is caused by bootstrap.min.css. As soon as I removed it, it goes away. The ripple not showing is because I tested with a Blazor Server project. I raised an issue for that: #45

**Comment by skclusive** [comment]
@henon again apologies for the delayed response. bootstrap css by default affects standard components someway. when we have conflicting css, checking the styles sources in browser devtools will be easier. and regarding ripple on server, will comment on the issue.

and great for start implementing new components.

**Comment by henon** [comment]
it is coming along nicely
![image](https://user-images.githubusercontent.com/44090/85223104-8b46ff00-b3c0-11ea-9492-521214d7f5e8.png)

**Comment by henon** [comment]
Chip is done:

![image](https://user-images.githubusercontent.com/44090/85224788-01e9f980-b3cd-11ea-8d8c-7393825fda0d.png)

**Comment by skclusive** [comment]
thanks for the great contribution. i am closing the issue.
