### ISSUE TITLE
Button: Ripple not working in Blazor Server

### ISSUE THREAD

**Issue by henon** [skclusive/Skclusive.Material.Component#45]
I tried a very simple Blazor Server project with only a few buttons and the ripple doesn't show when clicking on the buttons. When I create a Blazor WASM project with the same code the ripple works.

**Comment by skclusive** [comment]
thanks for raising the issue. ripple behaviour should work in server mode as well. i have been using  server side blazor for my personal projects. could you please share the sample code in a repo?

for server and webassembly projects, the configuration in statrup class should be different. i guess you may be already aware this repo https://github.com/skclusive/Skclusive.Blazor.Samples where we have sample projects each with all blazor hosting mode.

this sample is minimum code which is equivalent to standard blazor sample https://github.com/skclusive/Skclusive.Blazor.Samples/tree/master/Skclusive.Blazor.Material

**Comment by henon** [comment]
Thanks for making me aware of those startup samples, they are very important. I think they should be linked under "Getting Started" of the documentation page. 

Anyway, when I execute your example `Material.Server.Host` or `Material.ServerPrerendered.Host` the ripple does not work with the button on the counter page and also not with the list items in the drawer. 
It works with `Material.Browser.Host` though.

**Comment by skclusive** [comment]
yes. thats good idea to add it under "Getting Started". 

now that is surprising. could you please provide more details like which browser and dotnet env, any console errors in browser?

**Comment by henon** [comment]
* Chrome Version 83.0.4103.106 (Official Build) (64-bit)
* Windows 10
* .NET Standard 2.1 or .NET Core 3.1, makes no difference
* No messages in the JavaScript console

**Comment by henon** [comment]
Also tried the latest Firefox 77.0.1 (64-Bit)

Here in contrast to Chrome, the Ripple does *not* work in WASM. It also does not show in Server mode. There are no error messages in the console.

**Comment by skclusive** [comment]
oh ok. could you please check this issue discussion? https://github.com/skclusive/Skclusive.Material.Component/issues/28

**Comment by henon** [comment]
Hmm, executing in Release mode also doesn't show a ripple. 

So you develop on Mac right? I don't own a Mac so I can't compare. What can I do to investigate this?

**Comment by henon** [comment]
Or how about this? Instead of wasting time on this, why not replace the existing ripple with this one? 

https://codepen.io/finnhvman/pen/jLXKJw

**Comment by skclusive** [comment]
ripple with just css. this looks great. we could add it as alternative implementation with a paramter.  but i guess the Ripple component has been/will be used in other components and have features like where the ripples starts.

one of the nice feature of material-ui react implementation is, the components could be used to compose other components easily. ex: Complex button here using ButtonBase https://skclusive.github.io/Skclusive.Material.Docs/button. I am not sure how easy in other blazor material-ui library to replicate such component. so we want to follow material-ui as much as possible. so that we could easily implement a material-ui based app to blazor using skclusive-ui.

**Comment by henon** [comment]
I agree to keep close to material-ui where it is good. Hopefully we can somehow make it work on Server with browsers on Windows but I don't yet know how. You are not able to reproduce the problem?

**Comment by skclusive** [comment]
i guess issue due to culture info. fixed in develop branch https://github.com/skclusive/Skclusive.Material.Component/blob/develop/Button/src/Ripple/Ripple.razor.cs#L99.

**Comment by alidogan** [comment]
> i guess issue due to culture info. fixed in develop branch https://github.com/skclusive/Skclusive.Material.Component/blob/develop/Button/src/Ripple/Ripple.razor.cs#L99.

Can you publish the fix in nuget?

**Comment by skclusive** [comment]
Patch version 2.0.1 released with string culture formatting fix https://www.nuget.org/packages/Skclusive.Material.Component/2.0.1. docs and samples repo updated.

hope this helps. please do validate and close the issue

**Comment by skclusive** [comment]
closing the issue as fix is released
