### ISSUE TITLE
appending a class to the class attribute of a RenderFragment

### ISSUE THREAD

**Issue by henon** [skclusive/Skclusive.Material.Component#48]
@skclusive does your framework have a way to pass a class into a given user-defined RenderFragment? The RenderFragement component should append the class to its own classes.

**Comment by skclusive** [comment]
yes. we have that pattern used in components when ever required ex: Hidden component

Hidden component with Context for Child RenderFragment<IContext>

https://github.com/skclusive/Skclusive.Material.Component/blob/master/Hidden/src/Hidden/Hidden.cs#L92

and samples using the Hidden component with context class and their own classes.

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Hidden/Segments/BreakpointDown/BreakpointDownDemo.razor#L29

```html
<Hidden
      MediumDown>
      <Paper
            Class="@(context.Class + " demo-hidden-paper")">
            MediumDown
     </Paper>
</Hidden>
```

**Comment by henon** [comment]
I don't think that solves my problem. It is this: I forgot to import Avatar while developing so I didn't see this problem:

![image](https://user-images.githubusercontent.com/44090/85328830-b8cf9d80-b4d1-11ea-8512-1af80a784de9.png)

Here is the generated HTML. 
![image](https://user-images.githubusercontent.com/44090/85329063-15cb5380-b4d2-11ea-9293-9c6b5bd70da3.png)

The problem is, I can only control the size and color of the Avatar which is a RenderFragment if I can append the classes Chip-Avatar and Chip-Avatar-Primary at the end of Avatar's class list.

But that would require a framework pattern that allows to inject classes into *any component of this library*. The classes should be injected after the component's own classes but before the user-defined classes so the parent can overwrite css of the embedded child fragment but the user can override all.

**Comment by henon** [comment]
Of course an easy solution for this specific problem would be to use a cascading value and specifically implement the injection in Avatar, but that would tightly couple Chip and Avatar, which should be avoided if possible.

**Comment by skclusive** [comment]
sorry. i dont get the problem completely. could you share the component code?

let me share my understanding.

Chip.razor

<div class="@_Class" style="@_Style">
    <Avatar Class="Chip-Avatar" />
</div>

if the above is the use case, all components in skclusive-ui supports accepting Class and Style and RootRef.

the result would be class passed to avatar would be added end of the avatar class list. and by css order of classes does not matter. what matter is which class is defined later i guess. so user defined classes could be rendered after framework classes as in samples which could override component styles.

**Comment by henon** [comment]
Maybe I do it just like that. I have a Renderfragment now which doesn't allow me to add a class. 

The chip code is merged, so you can look at it.

**Comment by skclusive** [comment]
yea. checked the code and understood the issue now. 

i like cascading value to pass parameters for this issue. we already do this pattern between List and ListItem and also in FormLabel.

List and ListItem are tightly coupled and used together. here is it bit unique. Avatar could be used in standalone most of the time. 

i see two approaches now,

1) RenderFragement<IComponentContext> AvatarContent (we follow RenderFragment named Content as suffix)

**Chip.razor**
```html
  <div>
      @if (AvatarContent != null)
      {
           @AvatarContent.Invoke(new ComponentContext() { Class = "chip-avatar" });
      }
  </div>

```

Consumer.razor

```html
<Chip>
   <AvatarContent Context="avatarcontext">
        <Avatar Class="@($"custom-avatar {avatarcontext.Class}")" />
  </AvatarContent>
</Chip>
```

2. using Cascading value

**Chip.razor**
```html
  <div>
      @if (AvatarContent != null)
      {
          <CascadingValue Value="new AvatarContext() { Class = "chip-avatar" }">
           @AvatarContent
         </CascadingValue>
      }
  </div>

```
requires change in Avatar component to get context parameter and use those values.

Consumer.razor

```html
<Chip>
   <AvatarContent>
        <Avatar Class="custom-avatar" />
  </AvatarContent>
</Chip>
```
easy for consumers. AvatarContext could be used by Chip and other components too. we could make it generic as well in core components. only doubt i have is how Avatar would perform when used not under Cascading value in terms of performance. because i guess in react too much of cascading value might affect the overall performance of the app.

**Comment by henon** [comment]
I tried the first, which looks like whichcraft to me ;) and I can't get it to compile

![image](https://user-images.githubusercontent.com/44090/85626006-a473d800-b66c-11ea-80fa-61469df48b1c.png)

**Comment by skclusive** [comment]
yea. i was just reffering the pattern. we could use the Builder class the following way.

Chip.cs

```csharp
protected IComponentContext AvatarContext => new ComponentContextBuilder()
           .WithClass(_AvatarClass) // class variable for avatar
           .WithStyle(_AvatarStyle) // class variable for style
          .Build();
```

and in Chip.razor

```html
<div>
       @AvatarContent?.Invoke(AvatarContext);
</div>

```

similar usage in Hidden component https://github.com/skclusive/Skclusive.Material.Component/blob/master/Hidden/src/Hidden/Hidden.cs#L92

**Comment by henon** [comment]
sorry, I am way over my head with this. I now got this error message
![image](https://user-images.githubusercontent.com/44090/85793149-de101600-b734-11ea-839a-d4ddc80e01ce.png)

**Comment by skclusive** [comment]
no issues. let me check and i will patch the updates to Chip.

**Comment by skclusive** [comment]
requested pattern have been implemented in Avatar and Icons. 

https://github.com/skclusive/Skclusive.Material.Component/blob/develop/Chip/src/Chip/Chip.razor#L20

Parent.razor
```html
<CascadingValue
            Value="@(new AvatarContextBuilder().WithClass("Parent-Avatar-Class").Build())">
            @AvatarContent
    </CascadingValue>
```

Consumer.razor

```html
<Parent>
  <AvatarContent>
     <Avatar Class="Consumer-Avatar-Class">F</Avatar>
 </AvatarContent>
</Parent>
```

the result would be.

```html
<Avatar Class="Consumer-Avatar-Class Parent-Avatar-Class">F</Avatar>
```

**Comment by skclusive** [comment]
closing the issue as the requested patten implemented for Icons and Avatar. we could add respective component context when required.
