### ISSUE TITLE
How to using Tab component?

### ISSUE THREAD

**Issue by peteryulius** [skclusive/Skclusive.Material.Component#50]
How to use tab components? I get an error when typing TabPanel when using the tab component. What should I do to fix it?

![image](https://user-images.githubusercontent.com/8745284/86245730-19e32980-bbd4-11ea-8626-d10e41f979b7.png)

This is the result when I run the application. The tabs is not working when I clicked.
![image](https://user-images.githubusercontent.com/8745284/86246515-4f3c4700-bbd5-11ea-9e3f-8329e20e7c18.png)

![image](https://user-images.githubusercontent.com/8745284/86246844-dbe70500-bbd5-11ea-8465-ded2b204b0b7.png)

**Comment by skclusive** [comment]
TabPanel is user defined component used in documentation. i guess it is better to add it to the skclusive-ui as an option.

could you please refer this issue for details? https://github.com/skclusive/Skclusive.Material.Component/issues/26

**Comment by peteryulius** [comment]
It's work, nice. Thanks for your efforts, awesome.
