### ISSUE TITLE
Typography Responsive Size

### ISSUE THREAD

**Issue by Danielgfonseca** [skclusive/Skclusive.Material.Component#57]
Many congratulations @skclusive  for the work.

I am using cards and within the same Typography, if the text is very large is it possible that it will decrease in size to fit just one line?

![Captura de ecrã de 2020-08-29 15-43-58](https://user-images.githubusercontent.com/13136154/91639550-4e763480-ea0f-11ea-95ad-28797078698d.png)

**Comment by skclusive** [comment]
great. can you try with passing NoWrap property?

```html
<Typography NoWrap>
LONG TEXT HEREEE
</Typography>
```

**Comment by Danielgfonseca** [comment]
![Captura de ecrã de 2020-09-01 10-07-00](https://user-images.githubusercontent.com/13136154/91831784-65e63500-ec3c-11ea-9c85-68a002959c92.png)
Resolve is only on one line. 

But it cuts the text in excess, the idea was to reduce the size of the text to keep the text all. Example to Follow
![Efeito Pretendido](https://user-images.githubusercontent.com/13136154/91831827-71d1f700-ec3c-11ea-9be1-a310475cb95a.jpg)

**Comment by skclusive** [comment]
there is no direct support for this. like other components Typography accepts Class and Style param. could be implemented with custom css
