### ISSUE TITLE
Breaking changes in 5.0.0 release

### ISSUE THREAD

**Issue by skclusive** [skclusive/Skclusive.Material.Component#58]
place holder issue. need to update the breaking changes.

1. To remove @using Skclusive.Material.Script in _imports.razor and Skclusive.Script.DomHelpers is the replaced in .cs files

2. `<ThemeProvider />` updates. info here #66 

3. Badge parameter renamed to BadgeText. `<Badge Badge="10" />` renamed to `<Badge BadgeText="10" />`

4. MediaQueryMatcher, HistoryBackHelper, DetectThemeHelper and EventDelegator moved from Skclusive.Material.Script to Skclusive.Script.DomHelpers.

5. RegisterAsync and UnRegisterAsync methods are renamed to InitAsync and DisposeAsync respectively for MediaQueryMatcher, HistoryBackHelper, DetectThemeHelper and EventDelegator

6. remove `@using Skclusive.Material.Theme` from `_Imports.razor` to avoid `'Typography' is an ambiguous reference between 'Skclusive.Material.Theme.Typography' and 'Skclusive.Material.Typography.Typography'`

**Comment by cmorgado** [comment]
Out of curiosity what can we expect with 3.0?

**Comment by skclusive** [comment]
Better Style and Script loading (DI powered) ex: <InjectedStyles /> and <InjectedScripts /> can find all the styles and scripts registered and render the combined resources.

All components have their service extension method to register their dependency services and own services. ex: Dialog depends on Modal. If you want to use Dialog alone, we can just install the component and call it is service extensions. no need to find and add their styles and scripts. 

Theming layer matches materail-ui themeing (except Overrides). Custom Theming with only main colors is possible. material-ui theme json can be deserialised to Theme.

Chip component implemented.

hoping to add few more new components.

bug fixing.

**Comment by esso23** [comment]
Will it support net5.0?

**Comment by skclusive** [comment]
yes. develop branch is of net5.0 rc.1.

**Comment by morvaizo** [comment]
Do you have estimated time of release?

**Comment by skclusive** [comment]
i am planning to release after .NET 5 release. i guess Nov 10-12.

**Comment by Danielgfonseca** [comment]
> i am planning to release after .NET 5 release. i guess Nov 10-12.

:smiley: :smiley: :smiley: :smiley:

Anxiously waiting for the launch, if you need testers just say.

**Comment by skclusive** [comment]
thanks for the interest. though there are not much new components except styling refactoring, simplified standalone component usage and reactivity feature if mobx component used.

i am planning to release some new libraries related to data loading integration with system.reactive and skclusive mobx statetree and skclusive-ui :-)

**Comment by pherbel** [comment]
@skclusive 
Do you plan to publish packages is with .Net 5 RC2.
We would be happy to start testing it.

**Comment by skclusive** [comment]
@pherbel sure. i can make a preview build. will update.

**Comment by skclusive** [comment]
released a .NET 5 RC2 version. https://www.nuget.org/packages/Skclusive.Material.Component/5.0.0-rc1 

pumped the next version to 5.0.0 to match .NET version.

blazor samples and material.docs develop branches are updated. need to document the breaking changes.

**Comment by Danielgfonseca** [comment]
> released a .NET 5 RC2 version. https://www.nuget.org/packages/Skclusive.Material.Component/5.0.0-rc1
> 
> pumped the next version to 5.0.0 to match .NET version.
> 
> blazor samples and material.docs develop branches are updated. need to document the breaking changes.

Great News 😃

Will you also update the Samples on the server side version?

**Comment by skclusive** [comment]
@Danielgfonseca yes. samples and docs project develop branch updated with latest release.

**Comment by pherbel** [comment]
@skclusive Thanks! We appreciate your work. We will test it and give feedback.

**Comment by skclusive** [comment]
5.0.0-rc2 released with docs and samples master branch updated and hosted with dotnet-5.0.0-rc2 version.

Skclusive Dashboard (https://skclusive.github.io/Skclusive.Blazor.Samples/Dashboard/) version feels bit quicker. credits to dotnet-wasm updates.

**Comment by skclusive** [comment]
5.0.0-rc3 released with style related bug fixes. @esso23 thanks for reporting bugs.

including contribution from @viniwrubleski and @rhyskoedijk.

**Comment by rhyskoedijk** [comment]
Another breaking change I found is you'll need to remove `@using Skclusive.Material.Theme` from `_Imports.razor` or else you will get namespace conflicts. i.e.

`
'Typography' is an ambiguous reference between 'Skclusive.Material.Theme.Typography' and 'Skclusive.Material.Typography.Typography'
`

**Comment by skclusive** [comment]
@rhyskoedijk thanks. updated the notes.

**Comment by skclusive** [comment]
finally version 5.0.1 released with samples and docs repo updated to use 5.0.1. 

still documentation need to be updated about breaking changes and architecture changes in 5.0.1.

**Comment by skclusive** [comment]
released 5.2.0 with mobile blazor bindings support.

https://skclusive.medium.com/releasing-skclusive-ui-5-2-0-for-blazor-b05ad03c1d75

**Comment by skclusive** [comment]
breaking changes are added in the docs repo.

**Comment by skclusive** [comment]
closing the issue now. please feel free to re-open if required
