### ISSUE TITLE
What about TreeView component?

### ISSUE THREAD

**Issue by Oleg26Dev** [skclusive/Skclusive.Material.Component#6]
Sometimes need to have a component to work with hierarchical data.

It may be very useful to have a Tree/TreeView component. 
Something like this
https://github.com/ctrl-alt-d/BlazorServerTree

**Comment by skclusive** [comment]
yea sure.

as skclusive.material.component replicates react based material-ui implementation, planning to have this https://material-ui.com/components/tree-view/ tree-view component in version 3.0. 

working process version 2.0 is mainly focusing providing documentation. hopefully end of march.

also i am open to implement other components not available in material-ui.com.

**Comment by skclusive** [comment]
closing it now. will be tracked along with #19 when we start developing TreeView.
