### ISSUE TITLE
Open Menu with Button into Table Row

### ISSUE THREAD

**Issue by HClausing** [skclusive/Skclusive.Material.Component#62]
Hello.

First of all, congatulations for this big (and nice) work!

I have one doubt: How can I use a button for opening a Menu, when it's inside a table Row (with N rows) ?

Ex:

![image](https://user-images.githubusercontent.com/15158923/95242669-e113ab80-07e5-11eb-93cd-d7ca3d34647f.png)

I didn't understand the right way to create element references from button "..." and Menu instance.

By the moment, I using temporary buttons from outside.

Thanks.

**Comment by skclusive** [comment]
sorry for the delayed response. you can check the sample here.

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Menu/Segments/SimpleListMenu/SimpleListMenuDemo.razor#L10

you can have RootRef on each row which can be passed to the corresponding Menu. Hope this helps.

**Comment by HClausing** [comment]
Thansk you so much! I'll try!
