### ISSUE TITLE
TextField Outlined

### ISSUE THREAD

**Issue by jstojiljkovic** [skclusive/Skclusive.Material.Component#65]
Hi, 
I'm having trouble using Outlined TextField, seems like something is broken, I copy-pasted the source from the documentation 
https://skclusive.github.io/Skclusive.Material.Docs/text regarding Outlined but this is the result I'm getting, am I missing something here?

![image](https://user-images.githubusercontent.com/22980168/97808021-7038a580-1c64-11eb-924b-bff3ae85c922.png)

**Comment by skclusive** [comment]
thanks for reporting. would be related to the browser locale and .net ToString() method related. we have updated .ToString(CultureInfo.Invariant) as code base. will be addressed in next release candidates in few days.

**Comment by skclusive** [comment]
5.0.0-rc2 version of skclusive-ui released with this bug addressed. could you please verify with rc1 builds? 

https://github.com/skclusive/Skclusive.Blazor.Samples and https://github.com/skclusive/Skclusive.Material.Docs projects updated with latest release incase to refer.

**Comment by jstojiljkovic** [comment]
Yea, works well now.

Thanks.
