### ISSUE TITLE
Badge no longer works in v5.0.0

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#68]
Same thing as in https://github.com/skclusive/Skclusive.Material.Component/issues/67 worked with 3.0.2-preview1, does not work with 5.0.0-rc2

```html
<Badge Badge="@SomeProperty.ToString()" Color="@Color.Primary">
  <IconButton class="@IconButtonClass">
    <SomeIcon></SomeIcon>
  </IconButton>
</Badge>
```

SomeProperty.ToString() is "31", but no badge is displayed, just the icon. Again, this happens in application that has been updated as stated here: https://github.com/skclusive/Skclusive.Material.Component/issues/67#issuecomment-721133191

**Comment by skclusive** [comment]
thats bad. will check the changes from 3.0.2-preview1 to 5.0.0-rc2 and get back to you.

if possible can you share minimal repo to reproduce?

**Comment by skclusive** [comment]
Badge parameter was renamed to BadgeText. `<Badge Badge="10" />` renamed to `<Badge BadgeText="10" />`

could you please if this is the issue.

**Comment by esso23** [comment]
That fixed the issue.
Thanks
