### ISSUE TITLE
How to use my own png file in AppLayout.razor?

### ISSUE THREAD

**Issue by win32nipuh** [skclusive/Skclusive.Material.Component#7]
How can I use my own wwwroot\images\mylogo.png file instead of AppLayout.razor svg image as in Dashboard sample?

**Comment by skclusive** [comment]
you can provide img content for logo. either you can update the AppLayout.razor

<MainLayout>
    <LogoContent>
       <img src="./images/mylogo.png" />
    </LogoContent>
    <TitleContent>
        <Typography
            Style="flex-grow: 1; margin-left: 20px;"
            Variant="@TypographyVariant.H6"
            NoWrap>
            Your Title Here
        </Typography>
    </TitleContent>
  <SidebarContent>
  ....
 </SidebarContent>
<BodyContent>
   @Body
</BodyContent>
</MainLayout>

or replace the AppLogo.razor svg content with img.

<img src="./images/mylogo.png" />

**Comment by win32nipuh** [comment]
Thanx, I see, it works.

**Comment by win32nipuh** [comment]
Btw, this path does not work
<img src="./images/mylogo.png"/>
I use this:
<img src="./_content/Skclusive.Blazor.Dashboard.App.View/images/mylogo.png"/>

Is it possible to use your short path somehow ?

**Comment by skclusive** [comment]
if you put the images inside wwwroot of hosting app, you can use the short path. but in that case you have to copy the resources in all type of hosting apps. 

hence i have added the static resources in the view library app. 

one another approach is having a custom <AppImage component accepting relative path and pre append the static part.

example:

```html
AppImage.razor

@inherits MaterialComponentBase

<img class="@_Class" style="@_Style" src="@_Src" />

@code {
  [Parameter]
  public string Src { set; get; }

  private string _Src => $"./_content/Skclusive.Blazor.Dashboard.App.View/images/{Src}";
}

```

usage:

```html

AppLayout.razor

<AppImage Src="mylogo.png" Class="if custom css required" Style="color: inherit;" />

```

hope this helps.

**Comment by win32nipuh** [comment]
I have used this in AppLayout.razor
<AppImage Src="mylogo.png" Class="if custom css required" Style="color: inherit;" />

But there  is AppImage is not defined, it seems no some @using?

**Comment by skclusive** [comment]
No. AppImage is my recommendation for avoiding repeating the static portion of the image paths.

you can create it or name is differently.

Another approach is creating new service class and registering it inside Extension.cs then autowiring it required places.

Ex:

```cs
PathService.cs

public class PathService
{
      private static readonly string ResourcePath = "./_content/Skclusive.Blazor.Dashboard.App.View";

      public string GetPath(string resource) 
      {
           return $"{ResourcePath}/resource";
      }
}
```

then in Startup.cs configure method,

```cs
services.AddSingleton<PathService>();
``` 

then in any components.

```html
AppLayout.razor

@inject PathService PathService

<LogoContent>
    <img src="@(PathService.GetPath("images/mylogo.png"))"/>
</LogoContent>

```
