### ISSUE TITLE
Unable to upgrade to 5.2.0

### ISSUE THREAD

**Issue by Julianh9** [skclusive/Skclusive.Material.Component#80]
Unable to upgrade to 5.2.0 

I have followed the instructions for Migrating to 5.2.0 from 2.0.1.

But the skclusive styles are not showing on my test form.

I have included below the following:

1. Project file
2. Change to startup.cs
3. Picture and source of index.razor page
4. App.Razor File

Your help is much appreciated

I have included a Word document with all the details below:

(https://github.com/skclusive/Skclusive.Material.Component/files/5684376/Unable.to.upgrade.to.5.docx)

1. PROJECT FILE

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Skclusive.Material.Component" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>

2. CHANGE TO STARTUP - PLEASE NOTE THE TWO LINES COMMENTED OUT

`   services.TryAddMaterialServices(    new MaterialConfigBuilder()
                .WithIsServer(true)
                .WithIsPreRendering(false)
                .WithTheme(Theme.Dark)
                //.WithDisableBinding(false) 
                //.WithDisableConfigurer(false) 
                .Build()
                );`

3.
![image](https://user-images.githubusercontent.com/7427094/102006927-6c9d4180-3d2d-11eb-8431-5ca29d4d3d35.png)

`@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<div Style="flex-grow: 1;">
    <AppBar Position="@AppBarPosition.Static">
        <Toolbar>
            <IconButton Edge="@IconButtonEdge.Start"
                        Style="margin-right: 16px;"
                        Color="@Color.Inherit"
                        aria-label="menu">
                <MenuIcon />
            </IconButton>
            <Typography Variant="@TypographyVariant.H6"
                        Style="flex-grow: 1;">
                News
            </Typography>

            <Button Color="@Color.Inherit">
                Login
            </Button>
        </Toolbar>
    </AppBar>

    Skclusive AppBar - not displaying correctly
</div>`

4. APP RAZOR FIL

`    <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>

    </Router>

**Comment by skclusive** [comment]
`<ThemeProvider/>` is mandatory in >= 5.0.0. Could you confirm it is added in `App.razor`?

**Comment by skclusive** [comment]
Please check https://github.com/skclusive/Skclusive.Blazor.Samples/blob/master/Skclusive.Blazor.Reactive/Reactive.App.View/AppView.razor 

`Head` is optional in `<ThemeProvider />`.

**Comment by Julianh9** [comment]
Thank you very much - that sorted the problem.

While we are talking - are you intending to create an option selector (drop down) component in Skclusive?

**Comment by skclusive** [comment]
yes. Thats the priority. Popper component and Select component. will be developed in https://github.com/skclusive/Skclusive.Material.Lab repo.

**Comment by Julianh9** [comment]
Two more suggestions:
1. Multipart button (two or more clickable areas)
2. Field filter on the grid

regards
Julian Hoets

PS - You have created a magic product
