### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by kevinvenclovas** [skclusive/Skclusive.Material.Component#82]
Hello, where can i find the icon libery (Bootstrap?). Can you send me the link where you got the icons.
i want to add some new icons to my project.

**Comment by skclusive** [comment]
icons are svg based and are available here. https://github.com/skclusive/Skclusive.Material.Component/tree/master/Icon/src/Icons  

icons are ported from https://material-ui.com/components/material-icons/. not all are ported. should have been automated but ported manually. sources for the material-ui icons are here https://github.com/mui-org/material-ui/tree/next/packages/material-ui-icons/src
