### ISSUE TITLE
TabPanel not recognized as component

### ISSUE THREAD

**Issue by JEMasonMedia** [skclusive/Skclusive.Material.Component#90]
I have this:
builder.Services.TryAddTabServices(new MaterialConfigBuilder().Build());

I have this:
@using Skclusive.Material.Tab;

"TabPanel" not recognized as component. I'm using several different components and they all work fine bit for some reason this one isn't. Installed version 5.2.0.

Thanks for your help!

**Comment by JEMasonMedia** [comment]
neither of these work either.:

//builder.Services.TryAddAlertServices(new MaterialConfigBuilder().Build());
@*@using Skclusive.Material.Alert;*@

Figured this out. the docs don't say this is a separate package. just install and do the rest of the doc and your good.

**Comment by skclusive** [comment]
TabPanel is custom component added in material docs. you can find the source of it.

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Tabs/Segments/TabPanel/TabPanel.razor

**Comment by JEMasonMedia** [comment]
I made this one that worked very well, but yours is definitely more correct. 

```
<div style="display: @TabState"> @ChildContent </div>

@code {
    #nullable disable
    [Parameter]
    public object Value { get; set; }
    [Parameter]
    public int TabIndex { get; set; } = 0;
    [Parameter]
    public RenderFragment ChildContent { get; set; }

    public string TabState { get; set; } = "none";

    protected override void OnParametersSet()
    {
        TabState = TabIndex == Convert.ToInt32(Value) ? "block" : "none";
        base.OnParametersSet();
    }
}
```
